### ISSUE TITLE
[bug] version command information is not populate

### ISSUE THREAD

**Issue by jrasell** [jrasell/nomad-toast#2]
When running the nomad-toast version command no details have been correctly populated:

```
nomad-toast version nomad-toast
 Date:
 Commit:
 Branch:
 State:
 Summary:
```
